on:
  push:

jobs:
  package-deb:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7
    with:
      package_build_rules: |
        pkg: mytest
        image: "debian:bullseye"
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
  package-rpm:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7
    with:
      package_build_rules: |
        pkg: mytest
        image: "centos:7"
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
